"""
Collections Root Index Generator

Generates the landing index.html at the collections repository root (the
parent of COLLECTIONS_ROOT), one card per discovered collection. Card title
and description come from each collection's collection.json descriptor;
counts and links are discovered from the collection's outputs. Adding a
collection therefore never requires editing hand-written HTML.
"""

from datetime import datetime, timezone

from .base import PipelineStepBase
from . import config
from .index_generator import esc


def generate_collections_index_html() -> str:
    """Build the root landing page HTML across all discovered collections."""
    root = config.COLLECTIONS_ROOT.parent
    cards = []
    for name in config.COLLECTIONS:
        if name == "fixtures":
            continue
        descriptor = config.load_collection_descriptor(name)
        collection_path = config.get_collection_path(name)
        rel = collection_path.relative_to(root).as_posix()
        total = len(config.list_protocols(name))
        processed = len(config.list_ready_protocols(name))
        title = descriptor.get("title", name)
        description = descriptor.get("description", "")
        links = [f'<a href="{rel}/index.html">Collection index &rarr;</a>']
        if (collection_path / "activities.html").exists():
            links.append(f'<a href="{rel}/activities.html">Activities inventory &rarr;</a>')
        cards.append(f'''  <div class="card">
    <h3><a href="{rel}/index.html">{esc(title)}</a></h3>
    {f'<p>{esc(description)}</p>' if description else ''}
    <p class="counts"><b>{total}</b> protocols &middot; <b>{processed}</b> processed</p>
    <p class="links">{' '.join(links)}</p>
  </div>''')

    generated_at = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    cards_html = '\n'.join(cards)

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>SoA2USDM Collections</title>
<style>
  :root {{ --fg:#1a1a1a; --muted:#6b7280; --line:#e5e7eb; --accent:#2563eb; }}
  body {{ font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
         color:var(--fg); max-width:760px; margin:2.5rem auto; padding:0 1.25rem; line-height:1.55; }}
  h1 {{ font-size:1.6rem; margin-bottom:.25rem; }}
  h2 {{ font-size:1.05rem; margin-top:2rem; }}
  p.lead {{ color:var(--muted); margin-top:0; }}
  a {{ color:var(--accent); text-decoration:none; }}
  a:hover {{ text-decoration:underline; }}
  ul {{ padding-left:1.2rem; }}
  li {{ margin:.3rem 0; }}
  .card {{ border:1px solid var(--line); border-radius:10px; padding:.9rem 1.1rem; margin:.8rem 0; }}
  .card h3 {{ margin:0 0 .3rem; font-size:1.05rem; }}
  .card p {{ margin:.25rem 0; font-size:.92rem; }}
  .card .counts {{ color:var(--muted); }}
  .card .links a {{ display:inline-block; margin-right:1rem; font-weight:600; }}
  footer {{ margin-top:2.5rem; color:var(--muted); font-size:.85rem; border-top:1px solid var(--line); padding-top:1rem; }}
</style>
</head>
<body>
  <h1>SoA2USDM Collections</h1>
  <p class="lead">Machine-actionable Schedule of Activities (SoA) extractions from clinical trial protocols.</p>

  <p>This repository holds SoA extraction, resolution, and consolidation outputs produced with the
     <a href="https://github.com/kerfors/soa2usdm">soa2usdm</a> pipeline, organised as collections of studies.
     Source protocol PDFs are fetched from their canonical sources and are not stored here.</p>

  <h2>Collections</h2>
{cards_html}

  <p class="lead" style="font-size:.9rem">Each collection index is generated by the pipeline (from
     <code>studies_protocols.xlsx</code> plus discovered outputs) and is the single source of truth for the study
     list, per-layer pipeline status, and links to each protocol's consolidated SoA, resolved views, extraction JSON,
     and Excel intermediates.</p>

  <h2>Pipeline layers</h2>
  <ul>
    <li><strong>Layer&nbsp;1 &mdash; Extraction:</strong> SoA table(s) transcribed from the protocol PDF to
        <code>soa-table-extraction</code> JSON (single-pass, or a PDF&rarr;Excel&rarr;JSON path for large tables).</li>
    <li><strong>Corrections:</strong> human review findings applied as an auditable sidecar
        (<code>*_corrections.json</code>) &mdash; the raw extraction is never overwritten.</li>
    <li><strong>Layer&nbsp;2 &mdash; Resolve:</strong> IDs, hierarchy, and relationships derived per table.</li>
    <li><strong>Layer&nbsp;3 &mdash; Consolidate:</strong> cross-table integration, activity matching, annotation dedup.</li>
    <li><strong>Visualize:</strong> consolidated HTML for human review against the source SoA.</li>
  </ul>

  <footer>
    Generated {generated_at} by <code>soa2usdm.collections_index</code>.
    Built iteratively with Claude (Anthropic). Content under CC-BY-4.0.
  </footer>
</body>
</html>'''


class CollectionsIndexStep(PipelineStepBase):
    """Generate the collections-repo root index.html (all collections)."""

    step_name = "collections_index"

    def execute(self, data: dict) -> dict:
        try:
            html = generate_collections_index_html()
            output_file = config.COLLECTIONS_ROOT.parent / "index.html"
            output_file.write_text(html, encoding="utf-8")
            self._analytics.increment("collections_index_generated")
            return {"output_file": str(output_file), "status": "success"}
        except Exception as e:
            self._log_error(f"Collections index generation failed: {e}")
            return {"output_file": None, "status": "failed", "error": str(e)}


def main():
    html = generate_collections_index_html()
    output_file = config.COLLECTIONS_ROOT.parent / "index.html"
    output_file.write_text(html, encoding="utf-8")
    print(f"Wrote {output_file}")


if __name__ == "__main__":
    main()
